name: epic_failure
description: A new Flutter package project.
version: 0.0.1
author: Owen Donckers
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  equatable: ^1.1.1

dev_dependencies:
  build_runner: any
  test: ^1.14.2
